namespace Paloma;

public enum ImageType : byte
{
	NO_IMAGE_DATA = 0,
	UNCOMPRESSED_COLOR_MAPPED = 1,
	UNCOMPRESSED_TRUE_COLOR = 2,
	UNCOMPRESSED_BLACK_AND_WHITE = 3,
	RUN_LENGTH_ENCODED_COLOR_MAPPED = 9,
	RUN_LENGTH_ENCODED_TRUE_COLOR = 10,
	RUN_LENGTH_ENCODED_BLACK_AND_WHITE = 11
}
